version: "3.4"

services:
  todolist-client:
    image: todolist-client
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
