services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  server:
    image: todolist-server
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb:27017/todo-list
    ports:
      - 5000:5000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
